name: Bug report
description: Report a reproducible defect in behavior
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the report.
        Please include enough detail to reproduce the issue deterministically.

  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-sentence description of the bug.
      placeholder: repo.outline omits nested symbols in class scope
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
      description: What should have happened.
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
      description: What happened instead.
    validations:
      required: true

  - type: textarea
    id: repro_steps
    attributes:
      label: Reproduction steps
      description: Provide numbered steps and exact commands/requests.
      placeholder: |
        1. Run `repo-mcp --repo-root ...`
        2. Send request `{"id":"1","method":"repo.outline","params":{"path":"..."}}`
        3. Observe ...
    validations:
      required: true

  - type: textarea
    id: payloads
    attributes:
      label: Request/response evidence
      description: Include relevant JSON payloads and outputs.
      render: json

  - type: input
    id: version
    attributes:
      label: Version / commit
      description: Tag, release, or commit SHA tested.
      placeholder: main@abcdef1
    validations:
      required: true

  - type: input
    id: environment
    attributes:
      label: Environment
      description: OS, Python version, and runtime context.
      placeholder: Ubuntu 24.04, Python 3.12.8, local STDIO
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: Scope and impact
      description: Which tool(s), adapter(s), or security guarantees are affected?

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-flight checks
      options:
        - label: I confirmed this behavior against current `main` (or latest release).
          required: true
        - label: I searched existing issues for duplicates.
          required: true
        - label: I removed sensitive data from logs/payloads.
          required: true
